<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Utility\NestedArray;

/**
* hook_form_FORMID_alter
* Alter "Site Information" form. 
* A new form text field named "Site API Key" needs to be added to the "Site Information" form with the default value of “No API Key yet”.
* When this form is submitted, the value that the user entered for this field should be saved as the system variable named "siteapikey".
* A Drupal message should inform the user that the Site API Key has been saved with that value.
* When this form is visited after the "Site API Key" is saved, the field should be populated with the correct value.
* The text of the "Save configuration" button should change to "Update Configuration". 
*/
function sahinul_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state) {
    $form['site_information']['siteapikey'] = [
        '#type'=>'textfield',
        '#title'=>'Site API Key',
        '#placeholder'=>'No API Key yet',
        '#default_value'=>\Drupal::config('system.site')->get('siteapikey'),
    ];
    NestedArray::setValue($form, ['actions', 'submit', '#value'], 'Update Configuration');
    $form['#submit'][] = 'sahinul_siteinfo_submit';
}

/**
* Saving API key into system configuration.
*/
function sahinul_siteinfo_submit($form, FormStateInterface $form_state){
    $posted = $form_state->getValues();
    $config = \Drupal::service('config.factory')->getEditable('system.site');
    $config->set('siteapikey', $posted['siteapikey'])->save();
    \Drupal::messenger()->addMessage(t('Site API Key has been saved with @apik.',['@apik'=>(!empty($posted['siteapikey'])?$posted['siteapikey']:'NULL') ]), 'status');
}
